apiVersion: v1
kind: Secret
metadata:
  name: "my-secret"
  labels:
    "jenkins.io/credentials-type": "Username and password"
  annotations:
    "jenkins.io/credentials-description": ""
type: Opaque
stringData:
  user: qqq
  pass: www
